metadata_repository/app/routes/core.py
# Big Data Smart Socket
# Copyright (C) 2016 Clemson University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import traceback

from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for

from ..core import find_transfers, FindTransferError
from ..forms import FindTransfersForm
from ..models import Destination


routes = Blueprint("core", __name__)


######################################################################################################
#
# Misc routes
#
######################################################################################################


@routes.route("/")
def index():
    """Home page"""
    return redirect(url_for("data_sources.list_data_sources"))


@routes.route("/transfers", methods=["GET", "POST"])
def transfers():
    """
    Find available transfers for a URL.
    """
    form = FindTransfersForm(request.form)
    form.destination.choices = [("", "Unknown")] + [(d.label, d.label) for d in Destination.query.all()]

    results = []
    if request.method == "POST":
        error_message = None
        error_details = None
        if form.validate():
            try:
                destination = None
                if form.destination.data:
                    destination = Destination.query.filter(Destination.label == form.destination.data).first()
                results = find_transfers(form.url.data, form.available_mechanisms.data, destination)
            except FindTransferError as e:
                error_message = e.args[0]
            except Exception as e:
                traceback.print_exc()
                error_message = "Unable to find transfers"
        else:
            error_message = "Validation error"
            error_details = form.errors

        if "application/json" in request.headers.getlist("Accept"):
            return jsonify(transfers=results, error=dict(message=error_message, details=error_details))
        elif error_message:
            flash(error_message, "danger")

    return render_template("transfers.html.jinja", form=form, transfers=results)

metadata_repository/app/routes/data_sources.py
# Big Data Smart Socket
# Copyright (C) 2016 Clemson University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import math
import traceback

from flask import abort, Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_login import login_required
from sqlalchemy import func
from wtforms import validators

from .auth import admin_required
from ..forms import ConfirmDeleteForm, DataSourceForm, DataSourceSearchForm, UrlForm
from ..forms.subform_handling import process_form_with_options_subform, render_options_subform
from ..forms.validators import Unique
from ..models import db_session, DataSource
from ..util import render_matcher_description, render_transform_description, \
    available_transfer_mechanism_types, options_form_class_for_transfer_mechanism_type


routes = Blueprint("data_sources", __name__)


@routes.route("/data_sources")
def list_data_sources():
    """
    List all data sources in database.
    """
    page_num = int(request.args.get("page", 1))
    num_sources_per_page = 10
    data_sources = DataSource.query.limit(num_sources_per_page).offset((page_num - 1) * num_sources_per_page).all()
    total_num_sources = DataSource.query.count()
    total_num_pages = math.ceil(total_num_sources / num_sources_per_page)
    page_range = range(max(1, page_num - 3), min(total_num_pages, page_num + 3) + 1)
    return render_template("data_sources/index.html.jinja", data_sources=data_sources, page_num=page_num,
                           page_range=page_range, total_num_pages=total_num_pages)


@routes.route("/data_sources/new", methods=["GET", "POST"])
@login_required
@admin_required
def create_data_source():
    """
    Add a new data source to the database.
    """
    form = process_form_with_options_subform(DataSourceForm,
                                             "transfer_mechanism_type", "transfer_mechanism_options",
                                             options_form_class_for_transfer_mechanism_type)

    if request.method == "POST" and form.validate():
        source = DataSource(
            label=form.label.data,
            description=form.description.data,
            transfer_mechanism_type=form.transfer_mechanism_type.data
        )
        if "transfer_mechanism_options" in form._fields.keys() and form._fields["transfer_mechanism_options"]:
            source.transfer_mechanism_options = form._fields["transfer_mechanism_options"].data
        else:
            source.transfer_mechanism_options = {}

        try:
            db_session.add(source)
            db_session.commit()
            flash("Data source saved", "success")
            return redirect(url_for("data_sources.show_data_source", source_id=source.id))
        except:
            db_session.rollback()
            flash("Failed to save data source", "danger")
            traceback.print_exc()

    return render_template("data_sources/new.html.jinja", form=form)


@routes.route("/data_sources/<source_id>")
def show_data_source(source_id):
    """
    Show information about a specific data source.
    """
    data_source = DataSource.query.filter(DataSource.id == source_id).first() or abort(404)
    return render_template("data_sources/show.html.jinja", data_source=data_source,
                           render_matcher_description=render_matcher_description,
                           render_transform_description=render_transform_description)


@routes.route("/data_sources/<source_id>/test_match", methods=["GET", "POST"])
def test_data_source_url_match(source_id):
    """
    Test whether or not a URL matches a data source.
    """
    data_source = DataSource.query.filter(DataSource.id == source_id).first() or abort(404)
    form = UrlForm(request.form)

    if request.method == "POST" and form.validate():
        if data_source.matches_url(form.url.data):
            flash("URL matches", "success")
        else:
            flash("URL does not match", "danger")

    return render_template("data_sources/test_url.html.jinja", data_source=data_source, form=form)


@routes.route("/data_sources/<source_id>/edit", methods=["GET", "POST"])
@login_required
@admin_required
def edit_data_source(source_id):
    """
    For GET requests, show form for editing a data source.
    For POST requests, process form and update data source in database.
    """
    data_source = DataSource.query.filter(DataSource.id == source_id).first() or abort(404)

    label_validators = [validators.InputRequired(), Unique(DataSource, "label", lambda q: q.filter(DataSource.id != source_id))]
    form = process_form_with_options_subform(DataSourceForm,
                                             "transfer_mechanism_type", "transfer_mechanism_options",
                                             options_form_class_for_transfer_mechanism_type,
                                             editing_obj=data_source,
                                             form_init=lambda f: setattr(f.label, "validators", label_validators))

    if request.method == "POST" and form.validate():
        data_source.label = form.label.data
        data_source.description = form.description.data
        data_source.transfer_mechanism_type = form.transfer_mechanism_type.data
        if "transfer_mechanism_options" in form._fields.keys() and form._fields["transfer_mechanism_options"]:
            data_source.transfer_mechanism_options = form._fields["transfer_mechanism_options"].data
        else:
            data_source.transfer_mechanism_options = {}

        try:
            db_session.commit()
            flash("Data source updated", "success")
            return redirect(url_for("data_sources.show_data_source", source_id=source_id))
        except:
            db_session.rollback()
            flash("Failed to update data source", "danger")
            traceback.print_exc()

    return render_template("data_sources/edit.html.jinja", data_source=data_source, form=form)


@routes.route("/data_sources/<source_id>/delete", methods=["GET", "POST"])
@login_required
@admin_required
def delete_data_source(source_id):
    data_source = DataSource.query.filter(DataSource.id == source_id).first()
    form = ConfirmDeleteForm(request.form)

    if request.method == "POST" and form.validate():
        try:
            db_session.delete(data_source)
            db_session.commit()
            flash("Data source deleted", "success")
            return redirect(url_for("data_sources.list_data_sources"))
        except:
            db_session.rollback()
            flash("Failed to delete data source", "danger")
            traceback.print_exc()

    return render_template("data_sources/delete.html.jinja", data_source=data_source, form=form)


@routes.route("/data_sources/transfer_mechanism_options_form")
@login_required
@admin_required
def show_transfer_mechanism_options_form():
    """Show options form for a specific transfer mechanism type."""
    return render_options_subform(
        available_transfer_mechanism_types(),
        options_form_class_for_transfer_mechanism_type,
        "transfer_mechanism_options")


@routes.route("/data_sources/relations")
def data_source_relations():
    data_sources = DataSource.query.all()
    nodes = []
    links = []
    for ds in data_sources:
        nodes.append({"id": ds.id, "label": ds.label})
        for t in ds.transforms:
            links.append({"source": ds.id, "target": t.to_data_source_id})

    return render_template("data_sources/links.html.jinja", nodes=nodes, links=links)


@routes.route("/data_sources/search")
def search_data_sources():
    form = DataSourceSearchForm(q=request.args.get("q"))

    if form.validate():
        data_sources = DataSource.query.filter(func.lower(DataSource.label).like("%%%s%%" % form.q.data.lower())).all()

        if "application/json" in request.headers.getlist("Accept"):
            return jsonify(data_sources=[{"id": d.id, "label": d.label} for d in data_sources])
        else:
            return render_template("data_sources/search_results.html.jinja", data_sources=data_sources, form=form)
    else:
        if "application/json" in request.headers.getlist("Accept"):
            abort(400)
        else:
            return render_template("data_sources/search_results.html.jinja", data_sources=None, form=form)

metadata_repository/app/routes/test_files.py
# Big Data Smart Socket
# Copyright (C) 2016 Clemson University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import traceback

from flask import abort, Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_login import login_required

from .auth import admin_required
from ..forms import ConfirmDeleteForm, TransferTestFileForm
from ..models import db_session, DataSource, TransferTestFile


routes = Blueprint("test_files", __name__)


@routes.route("/data_sources/<source_id>/test_files")
def list_test_files(source_id):
    """
    List test files for a particular data source
    """
    data_source = DataSource.query.filter(DataSource.id == source_id).first() or abort(404)

    if request.headers.get("Accept") == "application/json":
        return jsonify(test_files=[f.url for f in data_source.transfer_test_files])
    else:
        return redirect(url_for("data_sources.show_data_source", source_id=source_id))


@routes.route("/data_sources/<source_id>/test_files/new", methods=["GET", "POST"])
@login_required
@admin_required
def add_test_file(source_id):
    """
    Add a new test file to a data source
    """
    data_source = DataSource.query.filter(DataSource.id == source_id).first() or abort(404)
    form = TransferTestFileForm(request.form)

    if request.method == "POST" and form.validate():
        test_file = TransferTestFile(
            data_source_id=data_source.id,
            file_id=len(data_source.transfer_test_files) + 1)
        form.populate_obj(test_file)

        if data_source.matches_url(test_file.url):
            try:
                db_session.add(test_file)
                db_session.commit()
                flash("Test file saved", "success")
                return redirect(url_for("data_sources.show_data_source", source_id=data_source.id))
            except:
                db_session.rollback()
                flash("Failed to save test file", "danger")
                traceback.print_exc()
        else:
            flash("Test file URL does not match data source", "danger")

    return render_template("test_files/new.html.jinja", data_source=data_source, form=form)


@routes.route("/data_sources/<source_id>/test_files/<file_id>")
def show_test_file(source_id, file_id):
    """
    Show information about a specific test file.
    """
    test_file = TransferTestFile.query.filter((TransferTestFile.data_source_id == source_id) & (TransferTestFile.file_id == file_id)).first() or abort(404)

    return render_template("test_files/show.html.jinja", test_file=test_file)


@routes.route("/data_sources/<source_id>/test_files/<file_id>/edit", methods=["GET", "POST"])
@login_required
@admin_required
def edit_test_file(source_id, file_id):
    """
    Edit a test file
    """
    data_source = DataSource.query.filter(DataSource.id == source_id).first() or abort(404)
    test_file = TransferTestFile.query.filter((TransferTestFile.data_source_id == source_id) & (TransferTestFile.file_id == file_id)).first() or abort(404)
    form = TransferTestFileForm(request.form, test_file)

    if request.method == "POST" and form.validate():
        form.populate_obj(test_file)

        if data_source.matches_url(test_file.url):
            try:
                db_session.commit()
                flash("Test file updated", "success")
                return redirect(url_for("test_files.show_test_file", source_id=data_source.id, file_id=test_file.file_id))
            except:
                db_session.rollback()
                flash("Failed to update test file", "danger")
                traceback.print_exc()
        else:
            flash("Test file URL does not match data source", "danger")

    return render_template("test_files/edit.html.jinja", test_file=test_file, form=form)


@routes.route("/data_sources/<source_id>/test_files/<file_id>/delete", methods=["GET", "POST"])
@login_required
@admin_required
def delete_test_file(source_id, file_id):
    """
    Delete a test file. Prompt for confirmation first.
    """
    data_source = DataSource.query.filter(DataSource.id == source_id).first() or abort(404)
    test_file = TransferTestFile.query.filter((TransferTestFile.data_source_id == source_id) & (TransferTestFile.file_id == file_id)).first() or abort(404)
    form = ConfirmDeleteForm(request.form)

    if request.method == "POST" and form.validate():
        try:
            db_session.delete(test_file)
            db_session.commit()
            flash("Test file deleted", "success")
            return redirect(url_for("data_sources.show_data_source", source_id=data_source.id))
        except:
            db_session.rollback()
            flash("Failed to delete test file", "danger")
            traceback.print_exc()

    return render_template("test_files/delete.html.jinja", form=form, test_file=test_file)

metadata_repository/app/templates/data_sources/delete.html.jinja
{% extends "layout.html.jinja" %}
{% import "form_macros.html.jinja" as form_macros %}

{% block page_header %}{{ data_source.label }}{% endblock %}

{% block content %}

<p>Are you sure you want to delete this data source? This cannot be undone.</p>

{{ form_macros.render_form(form, action_text="Delete", action_url=url_for("data_sources.delete_data_source", source_id=data_source.id), btn_class="btn btn-danger") }}

<p style="margin-top:20px;"><a class="btn btn-default" href="{{ url_for('data_sources.show_data_source', source_id=data_source.id) }}">Cancel</a></p>

{% endblock %}

metadata_repository/app/templates/data_sources/edit.html.jinja
{% extends "layout.html.jinja" %}
{% import "form_macros.html.jinja" as form_macros %}
{% from "form_handling_macros.html.jinja" import render_options_subform_js %}

{% block page_header %}Edit {{ data_source.label }}{% endblock %}

{% block content %}

{{ form_macros.render_form(form, action_url=url_for("data_sources.edit_data_source", source_id=data_source.id), btn_class="btn btn-primary") }}

<hr>

<a href="{{ url_for('data_sources.show_data_source', source_id=data_source.id) }}" class="btn btn-default">Cancel</a>

{% endblock %}

{% block scripts %}
{{ render_options_subform_js("transfer_mechanism_type", url_for('data_sources.show_transfer_mechanism_options_form')) }}
{% endblock %}

metadata_repository/app/templates/data_sources/index.html.jinja
{% extends "layout.html.jinja" %}

{% block page_header %}Data Sources{% endblock %}

{% block content %}

{% if data_sources|length > 0 %}
    <ul>
        {% for data_source in data_sources %}
            <li>
                <a href="{{ url_for('data_sources.show_data_source', source_id=data_source.id) }}">{{ data_source.label }}</a>
            </li>
        {% endfor %}
    </ul>

    {% if total_num_pages > 1 %}
        <nav style="text-align:center;">
            <ul class="pagination">
                {% if page_range[0] > 1 %}
                    <li><a href="{{ url_for('data_sources.list_data_sources', page=(page_range[0] - 1)) }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                {% endif %}
                {% for p in page_range %}
                    {% if p == page_num %}<li class="active">{% else %}<li>{% endif %}
                    <a href="{{ url_for('data_sources.list_data_sources', page=p) }}">{{ p }}</a></li>
                {% endfor %}
                {% if page_range[-1] < total_num_pages %}
                    <li><a href="{{ url_for('data_sources.list_data_sources', page=(page_range[-1] + 1)) }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% else %}
    <p>No data sources found.</p>
{% endif %}

<p><a href="{{ url_for('data_sources.search_data_sources') }}">Search Data Sources</a></p>
<p><a href="{{ url_for('data_sources.data_source_relations') }}">Show Relations</a></p>

{% if current_user.is_admin %}
<p><a href="{{ url_for('data_sources.create_data_source') }}">Add New Data Source</a></p>
{% endif %}
<p><a href="{{ url_for('core.transfers') }}">Find Alternate Data Sources</a></p>

{% endblock %}

metadata_repository/app/templates/data_sources/links.html.jinja
{% extends "layout.html.jinja" %}

{% block head %}
<style>
.node {
    fill: rgb(174,199,232);
    stroke: #fff;
    stroke-width: 1.5px;
}

.link {
    fill: none;
    stroke: #999;
    stroke-width: 4px;
    cursor: default;
}
</style>
{% endblock %}

{% block page_header %}Data Source Relations{% endblock %}

{% block content %}

{#
<pre>{{ nodes|tojson|safe }}</pre>
<pre>{{ links|tojson|safe }}</pre>
#}

<div id="graph-container" style="height:500px;width:100%;"></div>

{% endblock %}

{% block scripts %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.13/d3.min.js"></script>
<script>

var nodes = {{ nodes|tojson|safe }};
var links = {{ links|tojson|safe }};

var nodeIdToIndex = nodes.reduce(function(o, n, i) {
    o[n.id] = i;
    return o;
}, {});

links = links.map(function(l) {
    return { source: nodes[nodeIdToIndex[l.source]], target: nodes[nodeIdToIndex[l.target]] };
});

var width = 720;
var height = 500;

var svg = d3.select("#graph-container").append("svg")
    .attr("width", "100%")
    .attr("height", "100%")
    .attr("viewBox", "0 0 " + width + " " + height)
    .attr("preserveAspectRatio", "xMidYMid meet");

svg.append("svg:defs")
    .append("svg:marker")
        .attr("id", "end-arrow")
        .attr("viewBox", "0 -5 10 10")
        .attr("refX", 6)
        .attr("markerWidth", 3)
        .attr("markerHeight", 3)
        .attr("orient", "auto")
        .append("svg:path")
            .attr("d", "M0,-5L10,0L0,5")
            .attr("fill", "#999");

svg.append("svg:defs")
    .append("svg:marker")
        .attr("id", "start-arrow")
        .attr("viewBox", "0 -5 10 10")
        .attr("refX", 4)
        .attr("markerWidth", 3)
        .attr("markerHeight", 3)
        .attr("orient", "auto")
        .append("svg:path")
            .attr("d", "M10,-5L0,0L10,5")
            .attr("fill", "#999");

var force = d3.layout.force()
    .charge(-500)
    .linkDistance(120)
    .size([width, height]);

force
    .nodes(nodes)
    .links(links)
    .start();

var link = svg.selectAll(".link")
    .data(links)
    .enter().append("path")
        .attr("class", "link")
        .style("marker-end", "url(#end-arrow)");

var node = svg.selectAll(".node")
    .data(nodes)
    .enter().append("circle")
        .attr("class", "node")
        .attr("r", 10)
        .call(force.drag)

var labels = svg.selectAll(".label")
    .data(nodes)
    .enter().append("text")
        .attr("class", "label")
        .text(function(d) { return d.label; });

node.append("title")
    .text(function(d) { return d.label; });

force.on("tick", function() {

    link.attr("d", function(d) {
        var deltaX = d.target.x - d.source.x,
            deltaY = d.target.y - d.source.y,
            dist = Math.sqrt(deltaX * deltaX + deltaY * deltaY),
            normX = deltaX / dist,
            normY = deltaY / dist,
            sourcePadding = 12;//d.left ? 17 : 12,
            targetPadding = 17;//d.right ? 17 : 12,
            sourceX = d.source.x + (sourcePadding * normX),
            sourceY = d.source.y + (sourcePadding * normY),
            targetX = d.target.x - (targetPadding * normX),
            targetY = d.target.y - (targetPadding * normY);
        return "M" + sourceX + "," + sourceY + "L" + targetX + "," + targetY;
    });

    node.attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; });

    labels
        .attr("x", function(d) { return d.x; })
        .attr("y", function(d) { return d.y;})
});

</script>

{% endblock %}

metadata_repository/app/templates/data_sources/new.html.jinja
{% extends "layout.html.jinja" %}
{% import "form_macros.html.jinja" as form_macros %}
{% from "form_handling_macros.html.jinja" import render_options_subform_js %}

{% block page_header %}Add New Data Source{% endblock %}

{% block content %}

{{ form_macros.render_form(form, action_url=url_for("data_sources.create_data_source"), btn_class="btn btn-primary") }}

<hr>

<a href="{{ url_for('data_sources.list_data_sources') }}" class="btn btn-default">Cancel</a>

{% endblock %}

{% block scripts %}
{{ render_options_subform_js("transfer_mechanism_type", url_for('data_sources.show_transfer_mechanism_options_form')) }}
{% endblock %}

metadata_repository/app/templates/data_sources/search_results.html.jinja
{% extends "layout.html.jinja" %}
{% import "form_macros.html.jinja" as form_macros %}

{% block page_header %}Search Results{% endblock %}

{% block content %}

{{ form_macros.render_form(form, action_url=url_for("data_sources.search_data_sources"), btn_class="btn btn-primary", method="GET") }}

{% if data_sources != None %}
    <h4 style="margin-top:20px;">Matching data sources</h4>
    {% if data_sources|length > 0 %}
        <ul>
            {% for data_source in data_sources %}
                <li>
                    <a href="{{ url_for('data_sources.show_data_source', source_id=data_source.id) }}">{{ data_source.label }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No data sources found.</p>
    {% endif %}
{% endif %}

<hr>

<p style="margin-top:20px;"><a href="{{ url_for('data_sources.list_data_sources') }}"><span class="glyphicon glyphicon-chevron-left"></span>All Data Sources</a></p>

{% endblock %}

metadata_repository/app/templates/data_sources/show.html.jinja
{% extends "layout.html.jinja" %}

{% block page_header %}{{ data_source.label }}{% endblock %}

{% block content %}

<p>{{ data_source.description or "No description" }}</p>

<p><strong>Transfer mechanism type:</strong> {{ data_source.transfer_mechanism_type }}</p>

{% if data_source.transfer_mechanism_options %}
    <strong>Transfer Mechanism Options:</strong>
    <ul>
        {% for opt, val in data_source.transfer_mechanism_options.items() %}
            <li><strong>{{ " ".join(opt.capitalize().split("_")) }}:</strong> {{ val|e }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% if current_user.is_admin %}
<p><a href="{{ url_for('data_sources.edit_data_source', source_id=data_source.id) }}">Edit this data source</a></p>
<p><a href="{{ url_for('data_sources.delete_data_source', source_id=data_source.id) }}">Delete this data source</a></p>
{% endif %}

<h4>URL Matchers</h4>

<ul>
    {% for matcher in data_source.url_matchers %}
        <li>
            <a href="{{ url_for('matchers.show_url_matcher', source_id=data_source.id, matcher_id=matcher.matcher_id) }}">
                {{- render_matcher_description(matcher.matcher_type, matcher.matcher_options) -}}
            </a>
        </li>
    {% else %}
        <li>No matchers</li>
    {% endfor %}
</ul>

{% if current_user.is_admin %}
<p><a href="{{ url_for('matchers.add_url_matcher', source_id=data_source.id) }}">Add URL matcher</a></p>
{% endif %}

<p><a href="{{ url_for('data_sources.test_data_source_url_match', source_id=data_source.id) }}">Test a URL</a></p>

<hr>

<h4>Transforms</h4>
<p>Listed in order of preference</p>

<ul class="striped">
    {% for transform in data_source.transforms %}
        <li>
            <a href="{{ url_for('transforms.show_transform', source_id=data_source.id, transform_id=transform.transform_id) }}">
                {{- transform.to_data_source.label -}}<br>
                {{- render_transform_description(transform.transform_type, transform.transform_options) -}}
            </a>
            {%- if current_user.is_admin -%}
                <span class="pull-right" style="margin-top:-9px;">
                    <span style="display:inline-block;width:16px;">
                        {%- if not loop.first -%}
                            <a href="{{ url_for('transforms.edit_transform_order', source_id=data_source.id, transform_id=transform.transform_id, direction='up') }}">&#8679;</a>
                        {%- endif -%}
                    </span>
                    <span style="display:inline-block;width:16px;">
                        {%- if not loop.last -%}
                            <a href="{{ url_for('transforms.edit_transform_order', source_id=data_source.id, transform_id=transform.transform_id, direction='down') }}">&#8681;</a>
                        {%- endif -%}
                    </span>
                </span>
            {%- endif -%}
        </li>
    {% else %}
        <li>No transforms</li>
    {% endfor %}
</ul>

{% if current_user.is_admin %}
<p><a href="{{ url_for('transforms.add_transform', source_id=data_source.id) }}">Add URL transform</a></p>
{% endif %}

<hr>

<h4>Test Files</h4>

<ul>
    {% for test_file in data_source.transfer_test_files %}
        <li><a href="{{ url_for('test_files.show_test_file', source_id=data_source.id, file_id=test_file.file_id) }}">{{ test_file.url }}</a></li>
    {% else %}
        <li>No test files</li>
    {% endfor %}
</ul>

{% if current_user.is_admin %}
<p><a href="{{ url_for('test_files.add_test_file', source_id=data_source.id) }}">Add test file</a></p>
<hr>

<h4>Transfer Reports</h4>
<p><a href="{{ url_for('transfer_reports.list_transfer_reports', source_id=data_source.id) }}">View transfer reports</a></p>
{% endif %}

<hr>

<p style="margin-top:20px;"><a href="{{ url_for('data_sources.list_data_sources') }}"><span class="glyphicon glyphicon-chevron-left"></span>All Data Sources</a></p>

{% endblock %}

metadata_repository/app/templates/data_sources/test_url.html.jinja
{% extends "layout.html.jinja" %}
{% import "form_macros.html.jinja" as form_macros %}

{% block page_header %}{{ data_source.label }} - Test URL Match{% endblock %}

{% block content %}

{% if data_source.url_matchers|length > 0 %}
    {{ form_macros.render_form(form, action_url=url_for("data_sources.test_data_source_url_match", source_id=data_source.id), btn_class="btn btn-primary") }}
{% else %}
    <p>This data source has no URL matchers.</p>
{% endif %}

<hr>

<p style="margin-top:20px;"><a href="{{ url_for('data_sources.show_data_source', source_id=data_source.id) }}"><span class="glyphicon glyphicon-chevron-left"></span>Back</a></p>

{% endblock %}