metadata_repository/app/routes/auth.py
# Big Data Smart Socket
# Copyright (C) 2016 Clemson University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import traceback
from functools import wraps

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_app, current_user, login_required, login_user, logout_user

from ..forms import LoginForm, RegistrationForm
from ..models import db_session, User


routes = Blueprint("auth", __name__)


def admin_required(func):
    """
    Decorator to require admin rights to access a route
    """
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if request.method in set(["OPTIONS"]):
            return func(*args, **kwargs)
        elif current_app.login_manager._login_disabled:
            return func(*args, **kwargs)
        elif not current_user.is_admin:
            return render_template("errors/admin_permission_required.html.jinja"), 403
        return func(*args, **kwargs)
    return decorated_view


@routes.route("/login", methods=["GET", "POST"])
def login():
    """
    Login to the application.
    """
    if current_user and not current_user.is_anonymous:
        return redirect(url_for("core.index"))

    form = LoginForm(request.form)
    if request.method == "POST" and form.validate():
        user = User.query.filter(User.email == form.email.data).first()
        if user and user.verify_password(form.password.data):
            login_user(user, remember=True)
            return redirect(url_for("core.index"))
        else:
            flash("Invalid credentials", "danger")

    return render_template("users/login.html.jinja", form=form)


@routes.route("/register", methods=["GET", "POST"])
def register():
    """
    Register a new user account.
    """
    if current_user and not current_user.is_anonymous:
        return redirect(url_for("core.index"))

    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate():
        user = User(name=form.name.data, email=form.email.data)
        user.set_password(form.password.data)
        try:
            db_session.add(user)
            db_session.commit()
            login_user(user, remember=True)
            flash("Registration successful", "success")
            return redirect(url_for("core.index"))
        except:
            db_session.rollback()
            flash("Unable to register", "danger")
            traceback.print_exc()

    return render_template("users/register.html.jinja", form=form)


@routes.route("/logout")
@login_required
def logout():
    """
    Logout of the application.
    """
    logout_user()
    return redirect(url_for("core.index"))

metadata_repository/app/routes/core.py
# Big Data Smart Socket
# Copyright (C) 2016 Clemson University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import traceback

from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for

from ..core import find_transfers, FindTransferError
from ..forms import FindTransfersForm
from ..models import Destination


routes = Blueprint("core", __name__)


######################################################################################################
#
# Misc routes
#
######################################################################################################


@routes.route("/")
def index():
    """Home page"""
    return redirect(url_for("data_sources.list_data_sources"))


@routes.route("/transfers", methods=["GET", "POST"])
def transfers():
    """
    Find available transfers for a URL.
    """
    form = FindTransfersForm(request.form)
    form.destination.choices = [("", "Unknown")] + [(d.label, d.label) for d in Destination.query.all()]

    results = []
    if request.method == "POST":
        error_message = None
        error_details = None
        if form.validate():
            try:
                destination = None
                if form.destination.data:
                    destination = Destination.query.filter(Destination.label == form.destination.data).first()
                results = find_transfers(form.url.data, form.available_mechanisms.data, destination)
            except FindTransferError as e:
                error_message = e.args[0]
            except Exception as e:
                traceback.print_exc()
                error_message = "Unable to find transfers"
        else:
            error_message = "Validation error"
            error_details = form.errors

        if "application/json" in request.headers.getlist("Accept"):
            return jsonify(transfers=results, error=dict(message=error_message, details=error_details))
        elif error_message:
            flash(error_message, "danger")

    return render_template("transfers.html.jinja", form=form, transfers=results)

metadata_repository/app/routes/users.py
# Big Data Smart Socket
# Copyright (C) 2016 Clemson University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import math
import traceback

from flask import abort, Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from .auth import admin_required
from ..forms import ToggleUserPermissionsForm
from ..models import db_session, User


routes = Blueprint("users", __name__)


@routes.route("/users")
@login_required
@admin_required
def list_users():
    """
    List all users in database
    """
    page_num = int(request.args.get("page", 1))
    num_users_per_page = 10
    users = User.query.order_by(User.is_admin.desc()).order_by(User.name) \
        .limit(num_users_per_page).offset((page_num - 1) * num_users_per_page).all()
    total_num_users = User.query.count()
    total_num_pages = math.ceil(total_num_users / num_users_per_page)
    page_range = range(max(1, page_num - 3), min(total_num_pages, page_num + 3) + 1)
    return render_template("users/index.html.jinja", users=users, page_num=page_num, page_range=page_range,
                           total_num_pages=total_num_pages)


@routes.route("/users/<user_id>")
@login_required
@admin_required
def show_user(user_id):
    """
    Show information about a specific user
    """
    user = User.query.filter(User.user_id == user_id).first() or abort(404)
    return render_template("users/show.html.jinja", user=user)


@routes.route("/users/<user_id>/edit_permissions", methods=["GET", "POST"])
@login_required
@admin_required
def edit_user_permissions(user_id):
    """
    Grant/revoke admin permissions for a user
    """
    user = User.query.filter(User.user_id == user_id).first() or abort(404)
    form = ToggleUserPermissionsForm(request.form)

    if request.method == "POST" and form.validate():
        if user.user_id == current_user.user_id:
            flash("Unable to change your own permissions", "danger")
        else:
            user.is_admin = not user.is_admin
            try:
                db_session.commit()
                flash("Permissions updated", "success")
                return redirect(url_for("users.show_user", user_id=user.user_id))
            except:
                db_session.rollback()
                flash("Failed to update permissions", "danger")
                traceback.print_exc()

    return render_template("users/edit_permissions.html.jinja", form=form, user=user)

metadata_repository/app/templates/form_handling_macros.html.jinja
{%- macro render_options_subform_js(type_field_id, options_form_url) -%}

<script>
$("#{{ type_field_id }}").on('change', function(e) {

    var select = $(this);
    var module = select.val();

    $.ajax({
        url: "{{ options_form_url }}",
        data: {
            "type": module
        },
        dataType: "text",
        success: function(data) {
            var fieldset = $(data).find("fieldset");
            var group = select.closest(".form-group");
            group.nextAll("fieldset").eq(0).remove();
            fieldset.insertAfter(group);
        },
        error: function(err) {
            console.warn(err);
        }
    });

});
</script>

{%- endmacro -%}

metadata_repository/app/templates/form_macros.html.jinja
{#  #}
{%- macro render_field(field, label_visible=true) -%}
    {%- if (field.type == "FormField") -%}
        {{ render_form_field(field) }}
    {%- elif field.type == "FieldList" -%}
        {{ render_field_list(field) }}
    {%- elif field.type == "BooleanField" -%}
        {{ render_checkbox_field(field) }}
    {%- elif field.type == "RadioField" -%}
        {{ render_radio_field(field) }}
    {%- else -%}
        {{ render_default_field(field, label_visible) }}
    {%- endif -%}
{%- endmacro -%}

{%- macro render_field_errors_list(errors) -%}
    {%- for e in errors -%}
        <p class="help-block">{{ e }}</p>
    {%- endfor -%}
{%- endmacro -%}

{# Form fields #}
{%- macro render_form_field(field) -%}
    <fieldset id={{ field.id }} style="margin-bottom:15px;">
        <legend>{{ field.label }}</legend>
        {%- for subfield in field -%}
            {{ render_field(subfield) }}
        {%- else -%}
            <p>No options available</p>
        {%- endfor -%}
    </fieldset>
{%- endmacro -%}

{# Field list #}
{%- macro render_field_list(field) -%}
    <div>
        <label>{{ field.label.text }}</label>
        <ul id="{{ field.id }}-list">
            {%- for subfield in field -%}
                <li>{{ render_default_field_with_group(subfield, true, "&minus;") }}</li>
            {%- endfor -%}
        </ul>
        <div style="text-align:right;">
            <button class="btn btn-default" id="{{ field.id }}-add" type="button">&plus;</button>
        </div>
        <script>
        (function() {
            var list = $("#{{ field.id }}-list");
            var addButton = $("#{{ field.id }}-add");

            var refresh = function() {
                var removeButtons = list.find(".input-group-btn button");
                if (removeButtons.length === 1) {
                    removeButtons.attr("disabled", "disabled");
                } else {
                    removeButtons.removeAttr("disabled");
                }

                list.find("li").each(function(i) {
                    $(this).find("input")
                        .attr("id", "{{ field.id }}-" + i)
                        .attr("name", "{{ field.id }}-" + i);
                    $(this).find("label").attr("for", "{{ field.id }}-" + i);
                });
            }

            var bindRemoveButtons = function() {
                var removeButtons = list.find(".input-group-btn button");
                removeButtons.click(function() {
                    $(this).parents("li").remove();
                    refresh();
                });
            };

            addButton.click(function() {
                var newInput = $('<li>{{ render_default_field_with_group(field.entries[0], true, "&minus;")|replace("\n", "") }}</li>');
                newInput.find("input").val("");
                list.append(newInput);
                bindRemoveButtons();
                refresh();
            });

            bindRemoveButtons();
            refresh();
        })();
        </script>
    </div>
{%- endmacro -%}

{# Checkbox fields #}
{%- macro render_checkbox_field(field) -%}
    <div class="{% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        <div class="checkbox">
            <label for="{{ field.id }}">
                {{ field(type="checkbox", **kwargs) }} {{ field.label.text }}
            </label>
        </div>

        {{ render_field_errors_list(field.errors) }}
    </div>
{%- endmacro -%}

{# Radio fields #}
{%- macro render_radio_field(field) -%}
    {%- for value, label, _ in field.iter_choices() -%}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
            </label>
        </div>
    {%- endfor -%}
{%- endmacro -%}

{%- macro render_default_field_with_group(field, label_visible, btn_label, btn_class="default") -%}
    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {%- if label_visible -%}
            <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
        {%- endif -%}

        <div class="input-group">
            {{ field(class_="form-control", **kwargs) }}
            <span class="input-group-btn">
                <button class="btn btn-{{ btn_class }}" type="button">{{ btn_label }}</button>
            </span>
        </div>

        {%- if field.description -%}
            <p class="help-block" style="color:inherit;">{{ field.description }}</p>
        {%- endif -%}

        {{ render_field_errors_list(field.errors) }}
    </div>
{%- endmacro -%}

{%- macro render_default_field(field, label_visible) -%}
    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {%- if field.type != "HiddenField" and field.type !="CSRFTokenField" and label_visible -%}
            <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
        {%- endif -%}
        {%- if field.type == "FileField" -%}{# File inputs do not get "form-control" class #}
            {{ field(**kwargs) }}
        {%- else -%}
            {{ field(class_="form-control", **kwargs) }}
        {%- endif -%}
        {%- if field.description -%}
            <p class="help-block" style="color:inherit;">{{ field.description }}</p>
        {%- endif -%}
        {{ render_field_errors_list(field.errors) }}
    </div>
{%- endmacro %}


{# Form #}
{%- macro render_form(form, action_text="Submit", action_url="", btn_class="btn btn-default", class_="", enctype="application/x-www-form-urlencoded", method="POST") -%}
    <form method="{{ method }}" action="{{ action_url }}" role="form" class="{{ class_ }}" enctype="{{ enctype }}">
        {{ form.hidden_tag() if form.hidden_tag }}
        {%- if caller -%}
            {{ caller() }}
        {%- else -%}
            {%- for f in form -%}
                {{ render_field(f) }}
            {%- endfor -%}
        {%- endif -%}
        <input type="submit" class="{{ btn_class }}" value="{{ action_text }}">
    </form>
{%- endmacro -%}

metadata_repository/app/templates/layout.html.jinja
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style>
        .striped li {
            padding: 4px;
        }
        .striped li:nth-child(even) {
            background: #eee;
        }
    </style>

    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <title>{% block title %}BDSS{% endblock %}</title>

    {% block head %}
    {% endblock %}
</head>
<body>

    {% block header %}
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url_for('core.index') }}">BDSS</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user and current_user.is_authenticated %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ current_user.name }} <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    {%- if current_user.is_admin -%}
                                        <li><a href="{{ url_for('users.list_users') }}">Registered Users</a></li>
                                        <li role="separator" class="divider"></li>
                                    {%- endif -%}
                                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li>
                                <a href="{{ url_for('auth.login') }}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav">
                        {% block nav %}
                            {% with routes = [
                                    ('data_sources.list_data_sources', 'Data Sources'),
                                    ('destinations.list_destinations', 'Destinations'),
                                    ('configuration.index', 'Import/Export Configuration')
                                ]
                            %}
                                {% for endpoint, label in routes %}
                                    {% if request.endpoint == endpoint %}
                                        <li class="active"><a href="{{ url_for(endpoint) }}">{{ label }}</a></li>
                                    {% else %}
                                        <li><a href="{{ url_for(endpoint) }}">{{ label }}</a></li>
                                    {% endif %}
                                {% endfor %}
                            {% endwith %}
                        {% endblock %}
                    </ul>

                </div>
            </div>
        </div>
    {% endblock %}

    <div class="container" style="margin-top:50px;padding-bottom:30px;">

        {% block flash_messages %}
            <div style="margin-top:5px;margin-bottom:-25px;">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category or info }} alert-dismissable" role="alert" style="margin-bottom:0;padding:10px;">
                                <button aria-label="Close" class="close" data-dismiss="alert" style="right:0;" type="button"><span aria-hidden="true">&times;</span></button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        {% endblock %}

        <h1 class="page-header" style="font-size:24px;">{% block page_header %}BDSS{% endblock %}</h1>

        <div id="page-content">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock %}

    {# For select fields containing options with extended descriptions, show the description for the
       selected option in a paragraph below the select #}
    <script>
    $(document).ready(function() {
        var updateDescription = function() {
            var group = $(this).closest(".form-group");
            group.find("p.option-description").remove();
            group.append($("<p class=\"option-description help-block\">" + $(this).find("option:selected").data("description") + "</p>"));
        };
        $("select.option-descriptions").on("change", updateDescription).each(updateDescription);
    });
    </script>

</body>
</html>

metadata_repository/app/templates/options_form.html.jinja
{% import "form_macros.html.jinja" as form_macros %}

{{- form_macros.render_form(form) -}}

metadata_repository/app/templates/transfers.html.jinja
{% extends "layout.html.jinja" %}
{% import "form_macros.html.jinja" as form_macros %}

{% block page_header %}Find Data Transfers{% endblock %}

{% block content %}

{{ form_macros.render_form(form, action_url=url_for("core.transfers"), btn_class="btn btn-primary") }}

{% if transfers %}
    {% if transfers|length > 0 %}
        <hr>
        <ol>
            {% for t in transfers %}
                <li>{{ t.url }}<br>
                    Mechanism: {{ t.mechanism_name }}<br>
                    Options: {{ t.mechanism_options|tojson }}<br>
                    Data Source: {{ t.data_source_id }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No results</p>
    {% endif %}
{% endif %}

<hr>

<p style="margin-top:20px;"><a href="{{ url_for('core.index') }}"><span class="glyphicon glyphicon-chevron-left"></span>Back</a></p>

{% endblock %}